"""
NAMD configuration file generation for FEP simulations.

Generates:
  - NVT equilibration config
  - NPT equilibration config
  - Forward FEP production config (λ: 0 → 1)
  - Backward FEP production config (λ: 1 → 0)
  - Per-window independent configs for HPC submission

Based on the NAMD FEP tutorial workflow: single config with runFEP Tcl
procedure for desktop/small-cluster, or independent window configs for
batch submission.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Lambda schedule
# ---------------------------------------------------------------------------

# Recommended 16-window schedule: denser spacing near endpoints where
# dE/dλ changes most rapidly (electrostatics decoupling).
DEFAULT_LAMBDA_SCHEDULE = [
    0.0000, 0.0450, 0.0900, 0.14546, 0.22425, 0.30303,
    0.38182, 0.46061, 0.5394, 0.61819, 0.6970,
    0.77576, 0.85455, 0.9100, 0.9550, 1.0000,
]


def lambda_windows(n_windows: int = 16) -> list[tuple[float, float]]:
    """Generate (λ_i, λ_{i+1}) window pairs.

    If n_windows matches the default 16, uses the recommended uneven
    schedule. Otherwise uses even spacing.
    """
    if n_windows < 2:
        raise ValueError("Need at least 2 lambda states")
    if n_windows == len(DEFAULT_LAMBDA_SCHEDULE):
        lambdas = DEFAULT_LAMBDA_SCHEDULE
    else:
        step = 1.0 / (n_windows - 1)
        lambdas = [round(i * step, 10) for i in range(n_windows)]
    return [(lambdas[i], lambdas[i + 1]) for i in range(n_windows - 1)]


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

def render_template(template: str, **kwargs) -> str:
    """Replace @KEY@ placeholders in a template string."""
    result = template
    for key, value in kwargs.items():
        marker = f"@{key.upper()}@"
        result = result.replace(marker, str(value))
    unresolved = [w for w in result.split() if w.startswith("@") and w.endswith("@")]
    if unresolved:
        raise ValueError(f"Unresolved template markers: {unresolved}")
    return result


# ---------------------------------------------------------------------------
# NAMD config template (NVT equilibration)
# ---------------------------------------------------------------------------

NVT_EQUIL_TEMPLATE = """\
###################################################
# NVT EQUILIBRATION — @LEG@ leg
# Generated by fep_pipeline
###################################################

set temp                @TEMPERATURE@

# Force-field parameters
paraTypeCharmm          on
@PARAMETER_LINES@

exclude                 scaled1-4
1-4scaling              1.0

# Topology
structure               @PSF_FILE@

# Initial conditions
coordinates             @PDB_FILE@
temperature             $temp

# Output
outputenergies          @OUTPUT_FREQ@
outputtiming            @OUTPUT_FREQ@
outputpressure          @OUTPUT_FREQ@
restartfreq             @OUTPUT_FREQ@
XSTFreq                 @OUTPUT_FREQ@
dcdfreq                 @OUTPUT_FREQ@

outputname              @OUTPUT_NAME@
restartname             @OUTPUT_NAME@
binaryoutput            yes
binaryrestart           yes

# Constant-T
langevin                on
langevinTemp            $temp
langevinDamping         1.0

# PME
PME                     yes
PMETolerance            1.0e-5
PMEInterpOrder          4
PMEGridSpacing          1.0

# Periodic boundary
cellBasisVector1        @BOX_X@ 0.0 0.0
cellBasisVector2        0.0 @BOX_Y@ 0.0
cellBasisVector3        0.0 0.0 @BOX_Z@
cellOrigin              @BOX_OX@ @BOX_OY@ @BOX_OZ@

wrapAll                 on
wrapWater               on

# Space partitioning
stepspercycle           10
margin                  1.0

# Cutoffs
switching               on
switchdist              10.0
cutoff                  12.0
pairlistdist            14.0

# Integrator
timestep                2.0
fullElectFrequency      2
nonbondedFreq           1

# SHAKE
rigidbonds              all
rigidtolerance          0.000001
rigiditerations         400

# COM removal
ComMotion               no

# FEP
source                  ../fep.tcl
alch                    on
alchType                fep
alchFile                @FEP_FILE@
alchCol                 B
alchOutFile             @OUTPUT_NAME@.fepout
alchOutFreq             @FEP_OUT_FREQ@

alchVdwLambdaEnd        1.0
alchElecLambdaStart     0.5
alchVdWShiftCoeff       5.0
alchDecouple            off

alchEquilSteps          @ALCH_EQUIL_STEPS@
set numSteps            @NUM_STEPS@
set numMinSteps         @NUM_MIN_STEPS@

runFEPmin 0.0 0.0 0.0 $numSteps $numMinSteps $temp
"""

NPT_EQUIL_TEMPLATE = """\
###################################################
# NPT EQUILIBRATION — @LEG@ leg
# Generated by fep_pipeline
###################################################

set temp                @TEMPERATURE@

paraTypeCharmm          on
@PARAMETER_LINES@

exclude                 scaled1-4
1-4scaling              1.0

structure               @PSF_FILE@

coordinates             @PDB_FILE@
bincoordinates          @PREV_COOR@
binvelocities           @PREV_VEL@
extendedsystem          @PREV_XSC@

outputenergies          @OUTPUT_FREQ@
outputtiming            @OUTPUT_FREQ@
outputpressure          @OUTPUT_FREQ@
restartfreq             @OUTPUT_FREQ@
XSTFreq                 @OUTPUT_FREQ@
dcdfreq                 @OUTPUT_FREQ@

outputname              @OUTPUT_NAME@
restartname             @OUTPUT_NAME@
binaryoutput            yes
binaryrestart           yes

langevin                on
langevinTemp            $temp
langevinDamping         1.0

PME                     yes
PMETolerance            1.0e-5
PMEInterpOrder          4
PMEGridSpacing          1.0

wrapAll                 on
wrapWater               on

# Constant-P
LangevinPiston          on
LangevinPistonTarget    1.01325
LangevinPistonPeriod    100
LangevinPistonDecay     50
LangevinPistonTemp      $temp
StrainRate              0.0 0.0 0.0
useGroupPressure        yes
useFlexibleCell         no

stepspercycle           10
margin                  30.0

switching               on
switchdist              10.0
cutoff                  12.0
pairlistdist            14.0

timestep                2.0
fullElectFrequency      2
nonbondedFreq           1

rigidbonds              all
rigidtolerance          0.000001
rigiditerations         400

ComMotion               no

source                  ../fep.tcl
alch                    on
alchType                fep
alchFile                @FEP_FILE@
alchCol                 B
alchOutFile             @OUTPUT_NAME@.fepout
alchOutFreq             @FEP_OUT_FREQ@

alchVdwLambdaEnd        1.0
alchElecLambdaStart     0.5
alchVdWShiftCoeff       5.0
alchDecouple            off

alchEquilSteps          @ALCH_EQUIL_STEPS@
set numSteps            @NUM_STEPS@

runFEP 0.0 0.0 0.0 $numSteps
"""

PRODUCTION_TEMPLATE = """\
###################################################
# FEP PRODUCTION — @LEG@ leg, @DIRECTION@
# Generated by fep_pipeline
###################################################

set temp                @TEMPERATURE@

paraTypeCharmm          on
@PARAMETER_LINES@

exclude                 scaled1-4
1-4scaling              1.0

structure               @PSF_FILE@

coordinates             @PDB_FILE@
bincoordinates          @PREV_COOR@
binvelocities           @PREV_VEL@
extendedsystem          @PREV_XSC@

outputenergies          @OUTPUT_FREQ@
outputtiming            @OUTPUT_FREQ@
outputpressure          @OUTPUT_FREQ@
restartfreq             @OUTPUT_FREQ@
XSTFreq                 @OUTPUT_FREQ@
dcdfreq                 @OUTPUT_FREQ@

outputname              @OUTPUT_NAME@
restartname             @OUTPUT_NAME@
binaryoutput            yes
binaryrestart           yes

langevin                on
langevinTemp            $temp
langevinDamping         1.0

PME                     yes
PMETolerance            1.0e-5
PMEInterpOrder          4
PMEGridSpacing          1.0

wrapAll                 on
wrapWater               on

LangevinPiston          on
LangevinPistonTarget    1.01325
LangevinPistonPeriod    100
LangevinPistonDecay     50
LangevinPistonTemp      $temp
StrainRate              0.0 0.0 0.0
useGroupPressure        yes
useFlexibleCell         no

stepspercycle           10
margin                  1.0

switching               on
switchdist              10.0
cutoff                  12.0
pairlistdist            14.0

timestep                2.0
fullElectFrequency      2
nonbondedFreq           1

rigidbonds              all
rigidtolerance          0.000001
rigiditerations         400

ComMotion               no

source                  ../fep.tcl
alch                    on
alchType                fep
alchFile                @FEP_FILE@
alchCol                 B
alchOutFile             @OUTPUT_NAME@.fepout
alchOutFreq             @FEP_OUT_FREQ@

alchVdwLambdaEnd        1.0
alchElecLambdaStart     0.5
alchVdWShiftCoeff       5.0
alchDecouple            off

alchEquilSteps          @ALCH_EQUIL_STEPS@
set numSteps            @NUM_STEPS@

@RUN_FEP_COMMAND@
"""

# ---------------------------------------------------------------------------
# Independent window template (one λ pair per config)
# ---------------------------------------------------------------------------

INDEPENDENT_WINDOW_TEMPLATE = """\
###################################################
# FEP Window @WINDOW_INDEX@ — @LEG@ @DIRECTION@
# λ: @ALCH_LAMBDA@ → @ALCH_LAMBDA2@
###################################################

set temp                @TEMPERATURE@

paraTypeCharmm          on
@PARAMETER_LINES@

exclude                 scaled1-4
1-4scaling              1.0

structure               @PSF_FILE@

coordinates             @PDB_FILE@
bincoordinates          @PREV_COOR@
binvelocities           @PREV_VEL@
extendedsystem          @PREV_XSC@

outputenergies          @OUTPUT_FREQ@
outputtiming            @OUTPUT_FREQ@
outputpressure          @OUTPUT_FREQ@
restartfreq             @OUTPUT_FREQ@
XSTFreq                 @OUTPUT_FREQ@
dcdfreq                 @OUTPUT_FREQ@

outputname              @OUTPUT_NAME@
restartname             @OUTPUT_NAME@
binaryoutput            yes
binaryrestart           yes

langevin                on
langevinTemp            $temp
langevinDamping         1.0

PME                     yes
PMETolerance            1.0e-5
PMEInterpOrder          4
PMEGridSpacing          1.0

wrapAll                 on
wrapWater               on

LangevinPiston          on
LangevinPistonTarget    1.01325
LangevinPistonPeriod    100
LangevinPistonDecay     50
LangevinPistonTemp      $temp
StrainRate              0.0 0.0 0.0
useGroupPressure        yes
useFlexibleCell         no

stepspercycle           10
margin                  1.0

switching               on
switchdist              10.0
cutoff                  12.0
pairlistdist            14.0

timestep                2.0
fullElectFrequency      2
nonbondedFreq           1

rigidbonds              all
rigidtolerance          0.000001
rigiditerations         400

ComMotion               no

source                  ../fep.tcl
alch                    on
alchType                fep
alchFile                @FEP_FILE@
alchCol                 B
alchOutFile             @OUTPUT_NAME@.fepout
alchOutFreq             @FEP_OUT_FREQ@

alchVdwLambdaEnd        1.0
alchElecLambdaStart     0.5
alchVdWShiftCoeff       5.0
alchDecouple            off

alchLambda              @ALCH_LAMBDA@
alchLambda2             @ALCH_LAMBDA2@
alchEquilSteps          @ALCH_EQUIL_STEPS@

run                     @NUM_STEPS@
"""


# ---------------------------------------------------------------------------
# Config writer
# ---------------------------------------------------------------------------

def _parameter_block(parameter_files: list[str]) -> str:
    """Format parameter file lines for NAMD config."""
    return "\n".join(f"parameters              {p}" for p in parameter_files)


def _box_params_from_log(vmd_log_text: str) -> dict:
    """Extract box dimensions and center from VMD minmax/center output."""
    lines = vmd_log_text.strip().splitlines()
    result = {"box_x": 0.0, "box_y": 0.0, "box_z": 0.0,
              "box_ox": 0.0, "box_oy": 0.0, "box_oz": 0.0}
    for i, line in enumerate(lines):
        if "minmax" in line.lower() or "{" in line:
            continue
        parts = line.split()
        if len(parts) >= 3:
            try:
                vals = [float(p) for p in parts[-3:]]
                if i < 2:  # min, max
                    continue
                elif i == 2:  # center
                    result["box_ox"] = vals[0]
                    result["box_oy"] = vals[1]
                    result["box_oz"] = vals[2]
            except ValueError:
                pass
    return result


class NAMDConfigGenerator:
    """Generate NAMD configuration files for an FEP simulation."""

    def __init__(
        self,
        *,
        temperature: float = 300.0,
        parameter_files: Optional[list[str]] = None,
        output_freq: int = 100,
        fep_out_freq: int = 100,
        alch_equil_steps: int = 50000,
        nvt_steps: int = 50000,
        nvt_min_steps: int = 5000,
        npt_steps: int = 50000,
        prod_steps: int = 500000,
        prod_steps_per_window: int = 500000,
    ):
        self.temperature = temperature
        self.parameter_files = parameter_files or []
        self.output_freq = output_freq
        self.fep_out_freq = fep_out_freq
        self.alch_equil_steps = alch_equil_steps
        self.nvt_steps = nvt_steps
        self.nvt_min_steps = nvt_min_steps
        self.npt_steps = npt_steps
        self.prod_steps = prod_steps
        self.prod_steps_per_window = prod_steps_per_window

    def _base_kwargs(self, leg: str, psf_file: str, pdb_file: str,
                     fep_file: str, box_info: dict) -> dict:
        return {
            "temperature": self.temperature,
            "parameter_lines": _parameter_block(self.parameter_files),
            "leg": leg,
            "psf_file": psf_file,
            "pdb_file": pdb_file,
            "fep_file": fep_file,
            "output_freq": self.output_freq,
            "fep_out_freq": self.fep_out_freq,
            "alch_equil_steps": self.alch_equil_steps,
            "box_x": box_info.get("box_x", 0.0),
            "box_y": box_info.get("box_y", 0.0),
            "box_z": box_info.get("box_z", 0.0),
            "box_ox": box_info.get("box_ox", 0.0),
            "box_oy": box_info.get("box_oy", 0.0),
            "box_oz": box_info.get("box_oz", 0.0),
        }

    def write_nvt(
        self, output_dir: Path, leg: str, *,
        psf_file: str, pdb_file: str, fep_file: str,
        output_name: str, box_info: Optional[dict] = None,
    ) -> Path:
        """Write NVT equilibration config."""
        kwargs = self._base_kwargs(leg, psf_file, pdb_file, fep_file, box_info or {})
        kwargs.update(output_name=output_name, num_steps=self.nvt_steps,
                       num_min_steps=self.nvt_min_steps)
        content = render_template(NVT_EQUIL_TEMPLATE, **kwargs)
        path = output_dir / f"{output_name}.namd"
        path.write_text(content)
        return path

    def write_npt(
        self, output_dir: Path, leg: str, *,
        psf_file: str, pdb_file: str, fep_file: str,
        output_name: str, prev_coor: str, prev_vel: str, prev_xsc: str,
    ) -> Path:
        """Write NPT equilibration config."""
        kwargs = self._base_kwargs(leg, psf_file, pdb_file, fep_file, {})
        kwargs.update(output_name=output_name, num_steps=self.npt_steps,
                       prev_coor=prev_coor, prev_vel=prev_vel, prev_xsc=prev_xsc)
        content = render_template(NPT_EQUIL_TEMPLATE, **kwargs)
        path = output_dir / f"{output_name}.namd"
        path.write_text(content)
        return path

    def write_production(
        self, output_dir: Path, leg: str, direction: str, *,
        psf_file: str, pdb_file: str, fep_file: str,
        output_name: str, prev_coor: str, prev_vel: str, prev_xsc: str,
        lambda_start: float = 0.0, lambda_end: float = 1.0,
        n_windows: int = 16,
    ) -> Path:
        """Write FEP production config using runFEP Tcl procedure."""
        kwargs = self._base_kwargs(leg, psf_file, pdb_file, fep_file, {})
        step = (lambda_end - lambda_start) / (n_windows - 1)
        run_fep = f"runFEP {lambda_start} {lambda_end} {step} $numSteps"
        kwargs.update(
            output_name=output_name, direction=direction,
            num_steps=self.prod_steps_per_window,
            prev_coor=prev_coor, prev_vel=prev_vel, prev_xsc=prev_xsc,
            run_fep_command=run_fep,
        )
        content = render_template(PRODUCTION_TEMPLATE, **kwargs)
        path = output_dir / f"{output_name}.namd"
        path.write_text(content)
        return path

    def write_independent_windows(
        self, output_dir: Path, leg: str, direction: str, *,
        psf_file: str, pdb_file: str, fep_file: str,
        prev_coor: str, prev_vel: str, prev_xsc: str,
        n_windows: int = 16,
    ) -> list[Path]:
        """Write one config per lambda window for batch/hpc submission."""
        windows = lambda_windows(n_windows)
        paths: list[Path] = []
        for i, (lam, lam2) in enumerate(windows):
            kwargs = self._base_kwargs(leg, psf_file, pdb_file, fep_file, {})
            kwargs.update(
                window_index=i,
                direction=direction,
                output_name=f"fep_{direction}_{i:02d}",
                num_steps=self.prod_steps_per_window,
                prev_coor=prev_coor, prev_vel=prev_vel, prev_xsc=prev_xsc,
                alch_lambda=f"{lam:.6f}",
                alch_lambda2=f"{lam2:.6f}",
            )
            content = render_template(INDEPENDENT_WINDOW_TEMPLATE, **kwargs)
            path = output_dir / f"fep_{direction}_{i:02d}.namd"
            path.write_text(content)
            paths.append(path)
        return paths


# ---------------------------------------------------------------------------
# NAMD command builder
# ---------------------------------------------------------------------------

def namd_gpu_command(
    namd_binary: str = "namd3",
    config: str = "",
    cpus: int = 1,
    device: int = 0,
) -> str:
    """Build a NAMD GPU execution command line.

    ``cpus`` defaults to 1 deliberately. In GPU-resident mode essentially all
    work runs on the GPU, so extra PEs only add synchronization contention and
    throughput scales *inversely* with PE count. Measured on a V100 with the
    64651-atom 6I5I complex: +p1 75.8, +p2 59.5, +p4 27.2, +p8 13.2 ns/day.
    Do not raise this without re-benchmarking.

    NOTE: ``--GPUresident on`` is passed on the command line here rather than
    written into the config templates, so that the CPU path (``namd_cpu_command``
    / ``use_gpu=False``) keeps working with the same configs. Do NOT also add
    ``GPUresident`` to a generated config -- NAMD rejects it outright with
    "Multiple definitions of 'GPUresident'".
    """
    return (
        f"{namd_binary} +p{cpus} +setcpuaffinity "
        f"--GPUresident on +devices {device} {config}"
    )


def namd_cpu_command(
    namd_binary: str = "namd2",
    config: str = "",
    cpus: int = 4,
) -> str:
    """Build a NAMD CPU-only execution command line."""
    return f"{namd_binary} +p{cpus} {config}"


# ---------------------------------------------------------------------------
# fep.tcl helper generation
# ---------------------------------------------------------------------------

FEP_TCL_CONTENT = """\
# fep.tcl — runFEP procedure for NAMD alchemical FEP
# Runs multiple lambda windows sequentially within a single NAMD job.
# Usage in .namd file:  source ../fep.tcl
#                        runFEP <lambda_start> <lambda_end> <delta_lambda> <nsteps>

proc runFEP {lambda_start lambda_end dlambda nsteps} {
    set n_lambda [expr {int(($lambda_end - $lambda_start) / $dlambda + 0.5)}]
    for {set i 0} {$i < $n_lambda} {incr i} {
        set lambda1 [expr {$lambda_start + $i * $dlambda}]
        set lambda2 [expr {$lambda_start + ($i + 1) * $dlambda}]
        if {$lambda2 > $lambda_end} {set lambda2 $lambda_end}
        alchLambda  $lambda1
        alchLambda2 $lambda2
        print "Running FEP window: lambda $lambda1 -> $lambda2"
        run $nsteps
    }
}

proc runFEPmin {lambda_start lambda_end dlambda nsteps minsteps temp} {
    set n_lambda [expr {int(($lambda_end - $lambda_start) / $dlambda + 0.5)}]
    for {set i 0} {$i < $n_lambda} {incr i} {
        set lambda1 [expr {$lambda_start + $i * $dlambda}]
        set lambda2 [expr {$lambda_start + ($i + 1) * $dlambda}]
        if {$lambda2 > $lambda_end} {set lambda2 $lambda_end}
        alchLambda  $lambda1
        alchLambda2 $lambda2
        print "Running FEP window (min): lambda $lambda1 -> $lambda2"
        minimize $minsteps
        reinitvels $temp
        run $nsteps
    }
}
"""


def write_fep_tcl(output_dir: Path) -> Path:
    """Write the fep.tcl helper to the given directory."""
    path = output_dir / "fep.tcl"
    path.write_text(FEP_TCL_CONTENT)
    return path
