#!/usr/bin/csh
#PBS -l nodes=
#PBS -l mem=
#PBS -l walltime=
#PBS -o job.o
#PBS -e job.e
#

set system = site

namd2 equ_${system}.namd | tee equ_${system}.out > /dev/null


# FEP/λ-REMD
# Runing 5 ns (200 ps x 25)
set cnt = 0
set cntmax = 25


while ( ${cnt} <= ${cntmax} )
    if ( ${cnt} == 0 ) then
        namd2 +replicas 16 fep_${system}.conf --source FEP_remd_relative.namd +stdout output_${system}/%d/job${cnt}.%d.log
    else
        namd2 +replicas 16 restart_${cnt}.conf --source FEP_remd_relative.namd +stdout output_${system}/%d/job${cnt}.%d.log
    @cnt += 1
    endif
end

